FROM node:20-alpine as builder

ARG VITE_API_URL
ARG VITE_AUTH_URL
ARG VITE_API_KEY
ARG VITE_PROJECT_ID

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_AUTH_URL=$VITE_AUTH_URL
ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_PROJECT_ID=$VITE_PROJECT_ID

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]